version: '3'

services:
    backend:
        build:
            context: ../..
            dockerfile: docker/dev/Dockerfile.dev
        image: iftar-backend:dev
        container_name: iftar-backend-dev
        restart: always
        depends_on:
            - mongo-db
        ports:
            - '5000:5000'
        env_file:
            - ../../.env
        environment:
            - PORT=5000
            - DATABASE_URL=mongodb://admin:password@mongo-db:27017/iftar-db?authSource=admin
        volumes:
            - ../../:/home/app/

    mongo-db:
        image: mongo
        container_name: iftar-mongo-db
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express
        container_name: iftar-mongo-express
        restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
        ports:
            - '8081:8081'
        depends_on:
            - mongo-db
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo-db

volumes:
    mongo-data:
        driver: local
