FROM node:16.14-alpine

WORKDIR /home/app

RUN chown -R node:node /home/app
USER node

COPY package.json ./
COPY tsconfig.json ./

RUN npm install

COPY src ./src

EXPOSE 5000

CMD ["npm", "run", "dev"]