name: Build, Dockerize, Push to Docker Hub And Deploy to ACI

on:
  push:
    branches: 
      - "master"

jobs:
  Build-Push-To-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Setup Test environement
        run: docker-compose -f docker-compose.test.yml up -d
      - 
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: npm
      -
        name: Install dependencies
        run: npm install
      -
        name: Run Tests
        run: npm test
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .  
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iftar-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iftar-server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iftar-server:buildcache,mode=max
