name: Test CI

on:
  push: 
    branches:
      - "develop"
  pull_request:
    branches: 
      - "master"

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Setup Test environement
        run: docker-compose -f docker-compose.test.yml up -d
      -
        name: Run Tests
        run: npm test
