name: Deployment

on:
    push:
        branches:
            - 'deploy'

jobs:
    deploy:
        name: Pull the latest image version and deploy it
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull The latest image version From Docker Hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/iftar-backend:latest
        #   - name: Deploy to ###
