name: Deployment

on:
    push:
        branches:
            - 'deploy'

jobs:
    deploy:
        name: Pull the latest image version and deploy it
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull The latest image version From Docker Hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/iftar-backend:latest
        
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - name: Login to Degital occean Container Registry
              run: doctl registry login 
            - name: Tag the docker image to the degital occean regitery
              run: docker tag ${{ secrets.DOCKER_USERNAME }}/iftar-backend:latest registry.digitalocean.com/iftar/iftar-backend:latest
            - name: Push image to degital occean registery
              run: docker push registry.digitalocean.com/iftar/iftar-backend:latest
