name: Deployment

on:
    push:
        branches:
            - 'deploy'

jobs:
    deploy:
        name: Pull the latest image version and deploy it
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull The latest image version From Docker Hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/iftar-backend:latest
        
            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
            - name: Deploy docker image to DigitalOcean
              run: > 
                doctl compute droplet create 
                --image ${{ secrets.DOCKER_USERNAME }}/iftar-backend:latest
                --size s-1vcpu-1gb
                --env JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
                --env MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}
                --env CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}
                --name iftar-backend
